name: ollama_with_tools
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dart_console: ^4.1.0
  ollama_dart: ^0.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
